# DARK COLORS
COLOR_DE_FONDO_DARK = "#1a1b28"
COLOR_DE_TEXTO_DARK = "#ffffff"
COLOR_BOTONES_DARK = "#1e2435"
COLOR_BOTONES_ESPECIALES_DARK = "#52c9dc"
COLOR_CAJA_TEXTO_DARK = "#1e1b28"

# LIGHT COLORS
COLOR_DE_FONDO_LIGHT = "#ffffff"
COLOR_DE_TEXTO_LIGHT = "#000000"
COLOR_BOTONES_ESPECIALES_LIGHT = "#52c9dc"
COLOR_BOTONES_LIGHT = "#f2f8fc"
COLOR_CAJA_TEXTO_LIGHT = "#ffffff"
